/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje2basliyoruz;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author sevkikaragol
 */
public class KullanıcıxBilg extends javax.swing.JFrame {
   int sayac=0;
   
    Oyuncu pc=new BilgisayarOyuncusu("1","Bilgisayar",0);
    Oyuncu kullanici=new InsanOyuncusu("2","Kullanici",0);
    ArrayList<Pokemon>liste=new ArrayList<Pokemon>();
    ArrayList<Integer>sayilar = new ArrayList<>();
    ArrayList<Integer>rastgelekart = new ArrayList<>();
    
    /**
     * Creates new form KullanıcıxBilg
     */
    public KullanıcıxBilg() {
      
        
        initComponents();
        
        Pokemon pikachu=new Pikachu("0","Pikachu","Elektrik");
        Pokemon bulbasaur=new Bulbasaur("1","Bulbasaur","Çim");
        Pokemon charmender=new Charmander("2","Charmender","Ateş");
        Pokemon squirtle=new Squirtle("3","Squirtle","Su");
        Pokemon zubat=new Zubat("4","Zubat","Hava");
        Pokemon psyduck=new Psyduck("5","Psyduck","Su");
        Pokemon snorlax=new Snorlax("6","Snorlax","Normal");
        Pokemon butterfree=new Butterfree("7","Butterfree","Hava");
        Pokemon jigglypuff=new Jigglypuff("8","Jigglypuff","Ses");
        Pokemon meowth=new Meowth("9","Meowth","Normal");
        liste.add(pikachu);
        liste.add(bulbasaur);
        liste.add(charmender);
        liste.add(squirtle);
        liste.add(zubat);
        liste.add(psyduck);
        liste.add(snorlax);
        liste.add(butterfree);
        liste.add(jigglypuff);
        liste.add(meowth);
        
        
        
        
        
      
       for (int i=0; i <10; i++) {
        sayilar.add(i);
        }
        Collections.shuffle(sayilar); //arrayList içinde bulunan sayiları karma
     
   
      jButton1.setIcon(liste.get(sayilar.get(0)).getIcon());
      jButton2.setIcon(liste.get(sayilar.get(1)).getIcon());
      jButton3.setIcon(liste.get(sayilar.get(2)).getIcon());
      jButton4.setIcon(liste.get(sayilar.get(3)).getIcon());
      jButton5.setIcon(liste.get(sayilar.get(4)).getIcon());
      jButton6.setIcon(liste.get(sayilar.get(5)).getIcon());
      jButton7.setIcon(liste.get(sayilar.get(6)).getIcon());
      jButton8.setIcon(liste.get(sayilar.get(7)).getIcon());
      jButton9.setIcon(liste.get(sayilar.get(8)).getIcon());
      jButton10.setIcon(liste.get(sayilar.get(9)).getIcon());
  
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jButton14.setVisible(false);
        jButton16.setVisible(false);
        jButton17.setVisible(false);
        jButton18.setVisible(true);
      
            
        
        
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1800, 1013));
        setMinimumSize(new java.awt.Dimension(1800, 1013));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 240, 200, 279);
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 160, 200, 279);
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 80, 200, 279);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 10, 200, 279);
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 10, 200, 279);
        getContentPane().add(jButton6);
        jButton6.setBounds(550, 10, 200, 279);
        getContentPane().add(jButton7);
        jButton7.setBounds(760, 10, 200, 279);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(350, 720, 200, 279);

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(560, 720, 200, 279);

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(770, 720, 200, 279);

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(980, 720, 200, 279);

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(1190, 720, 200, 279);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokeimg/cardframe.png"))); // NOI18N
        getContentPane().add(jButton13);
        jButton13.setBounds(1570, 130, 200, 279);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokeimg/cardframe.png"))); // NOI18N
        getContentPane().add(jButton14);
        jButton14.setBounds(1570, 420, 200, 279);

        jButton15.setText("Kartları dağıt!");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(1640, 10, 150, 50);
        getContentPane().add(jButton16);
        jButton16.setBounds(970, 10, 200, 279);
        getContentPane().add(jButton17);
        jButton17.setBounds(1180, 10, 200, 279);

        jButton18.setText("Kazananı göster!");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(1640, 890, 150, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokeimg/gamearea.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1800, 1013);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1800, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
//Kartları dagıtma butonu
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        jButton15.setVisible(false);
    
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       
       sayac=sayac+1;
       
        
        
        if(sayac==1){
        jButton8.setVisible(false);
        jButton14.setIcon(liste.get(sayilar.get(7)).getIcon());
        jButton5.setVisible(false);
        jButton13.setIcon(liste.get(sayilar.get(4)).getIcon());
            jButton4.setVisible(false);
            jButton3.setVisible(false);
            jButton11.setVisible(true);
            jButton16.setVisible(true);
        jButton11.setIcon(liste.get(sayilar.get(3)).getIcon());
        jButton16.setIcon(liste.get(sayilar.get(2)).getIcon());
        if(liste.get(sayilar.get(7)).getHasarPuani()>liste.get(sayilar.get(4)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(4)).getHasarPuani()>liste.get(sayilar.get(7)).getHasarPuani()){
            pc.setSkor(5);
        }
            
           
        }
        
        if(sayac==2){
         jButton12.setIcon(liste.get(sayilar.get(1)).getIcon());
         jButton17.setIcon(liste.get(sayilar.get(0)).getIcon());
         jButton14.setIcon(liste.get(sayilar.get(7)).getIcon());
         jButton13.setIcon(liste.get(sayilar.get(4)).getIcon());
        
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButton12.setVisible(true);
            jButton17.setVisible(true);
            jButton8.setVisible(false);
            jButton5.setVisible(false);
         if(liste.get(sayilar.get(7)).getHasarPuani()>liste.get(sayilar.get(4)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(4)).getHasarPuani()>liste.get(sayilar.get(7)).getHasarPuani()){
            pc.setSkor(5);
        }
           
            
        }
        else if(sayac>2){
            jButton8.setVisible(false);
            jButton5.setVisible(false);
            jButton14.setIcon(liste.get(sayilar.get(7)).getIcon());
            jButton13.setIcon(liste.get(sayilar.get(4)).getIcon());
        if(liste.get(sayilar.get(7)).getHasarPuani()>liste.get(sayilar.get(4)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(4)).getHasarPuani()>liste.get(sayilar.get(7)).getHasarPuani()){
            pc.setSkor(5);
        }
            
        }
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      sayac=sayac+1;
       
        
        
        if(sayac==1){
        jButton9.setVisible(false);
        jButton14.setIcon(liste.get(sayilar.get(8)).getIcon());
        jButton6.setVisible(false);
        jButton13.setIcon(liste.get(sayilar.get(5)).getIcon());
            jButton4.setVisible(false);
            jButton3.setVisible(false);
            jButton11.setVisible(true);
            jButton16.setVisible(true);
        jButton11.setIcon(liste.get(sayilar.get(3)).getIcon());
        jButton16.setIcon(liste.get(sayilar.get(2)).getIcon());
         if(liste.get(sayilar.get(8)).getHasarPuani()>liste.get(sayilar.get(5)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(5)).getHasarPuani()>liste.get(sayilar.get(8)).getHasarPuani()){
            pc.setSkor(5);
        }
           
        }
        
        if(sayac==2){
         jButton12.setIcon(liste.get(sayilar.get(1)).getIcon());
         jButton17.setIcon(liste.get(sayilar.get(0)).getIcon());
         jButton14.setIcon(liste.get(sayilar.get(8)).getIcon());
         jButton13.setIcon(liste.get(sayilar.get(5)).getIcon());
        
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButton12.setVisible(true);
            jButton17.setVisible(true);
            jButton9.setVisible(false);
            jButton6.setVisible(false);
          if(liste.get(sayilar.get(8)).getHasarPuani()>liste.get(sayilar.get(5)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(5)).getHasarPuani()>liste.get(sayilar.get(8)).getHasarPuani()){
            pc.setSkor(5);
        }
           
        }
        else if(sayac>2){
            jButton9.setVisible(false);
            jButton6.setVisible(false);
            jButton14.setIcon(liste.get(sayilar.get(8)).getIcon());
            jButton13.setIcon(liste.get(sayilar.get(5)).getIcon());
          if(liste.get(sayilar.get(8)).getHasarPuani()>liste.get(sayilar.get(5)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(5)).getHasarPuani()>liste.get(sayilar.get(8)).getHasarPuani()){
            pc.setSkor(5);
        }
            
        }

        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        sayac=sayac+1;
       
        
        
        if(sayac==1){
        jButton10.setVisible(false);
        jButton14.setIcon(liste.get(sayilar.get(9)).getIcon());
        jButton7.setVisible(false);
        jButton13.setIcon(liste.get(sayilar.get(6)).getIcon());
            jButton4.setVisible(false);
            jButton3.setVisible(false);
            jButton11.setVisible(true);
            jButton16.setVisible(true);
            jButton11.setIcon(liste.get(sayilar.get(3)).getIcon());
            jButton16.setIcon(liste.get(sayilar.get(2)).getIcon());
        
        if(liste.get(sayilar.get(9)).getHasarPuani()>liste.get(sayilar.get(6)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(6)).getHasarPuani()>liste.get(sayilar.get(9)).getHasarPuani()){
            pc.setSkor(5);
        }    
            
        
        }
        
        if(sayac==2){
         jButton12.setIcon(liste.get(sayilar.get(1)).getIcon());
         jButton17.setIcon(liste.get(sayilar.get(0)).getIcon());
         jButton14.setIcon(liste.get(sayilar.get(9)).getIcon());
         jButton13.setIcon(liste.get(sayilar.get(6)).getIcon());
        
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButton12.setVisible(true);
            jButton17.setVisible(true);
            jButton10.setVisible(false);
            jButton7.setVisible(false);
        
        if(liste.get(sayilar.get(9)).getHasarPuani()>liste.get(sayilar.get(6)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(6)).getHasarPuani()>liste.get(sayilar.get(9)).getHasarPuani()){
            pc.setSkor(5);
        }
           
            
        }
        else if(sayac>2){
        jButton10.setVisible(false);
        jButton7.setVisible(false);
        jButton14.setIcon(liste.get(sayilar.get(9)).getIcon());
        jButton13.setIcon(liste.get(sayilar.get(6)).getIcon());
        
        if(liste.get(sayilar.get(9)).getHasarPuani()>liste.get(sayilar.get(6)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(6)).getHasarPuani()>liste.get(sayilar.get(9)).getHasarPuani()){
            pc.setSkor(5);
        }
            
        }
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       sayac=sayac+1;
        if(sayac==2){
         jButton12.setIcon(liste.get(sayilar.get(1)).getIcon());
         jButton17.setIcon(liste.get(sayilar.get(0)).getIcon());
         jButton14.setIcon(liste.get(sayilar.get(3)).getIcon());
         jButton13.setIcon(liste.get(sayilar.get(2)).getIcon());
        
            jButton2.setVisible(false);
            jButton1.setVisible(false);
            jButton12.setVisible(true);
            jButton17.setVisible(true);
            jButton11.setVisible(false);
            jButton16.setVisible(false);
        if(liste.get(sayilar.get(3)).getHasarPuani()>liste.get(sayilar.get(2)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(2)).getHasarPuani()>liste.get(sayilar.get(3)).getHasarPuani()){
            pc.setSkor(5);
        }
           
            
        }
        else if(sayac>2){
            jButton11.setVisible(false);
            jButton16.setVisible(false);
            jButton14.setIcon(liste.get(sayilar.get(3)).getIcon());
            jButton13.setIcon(liste.get(sayilar.get(2)).getIcon());
        
        if(liste.get(sayilar.get(1)).getHasarPuani()>liste.get(sayilar.get(0)).getHasarPuani()){
            kullanici.setSkor(5);
        }
        else if(liste.get(sayilar.get(0)).getHasarPuani()>liste.get(sayilar.get(1)).getHasarPuani()){
            pc.setSkor(5);
        }
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton12.setVisible(false);
        jButton17.setVisible(false);
        jButton14.setIcon(liste.get(sayilar.get(1)).getIcon());
        jButton13.setIcon(liste.get(sayilar.get(0)).getIcon());
    if(liste.get(sayilar.get(1)).getHasarPuani()>liste.get(sayilar.get(0)).getHasarPuani()){
            kullanici.setSkor(5);
        }
    else if(liste.get(sayilar.get(0)).getHasarPuani()>liste.get(sayilar.get(1)).getHasarPuani()){
            pc.setSkor(5);
        }
      
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       jButton18.setVisible(false);
        String kazanan;
        jButton13.setVisible(false);
       jButton14.setVisible(false);
       if(kullanici.getSkor()>pc.getSkor()){
           kazanan=kullanici.getOyuncuAdi();
       }else
           kazanan=pc.getOyuncuAdi();
        JOptionPane panel=new JOptionPane();
        panel.showMessageDialog(null,"\nBilgisayarin skoru:"+pc.getSkor()+
                "\nKullanici skoru:"+kullanici.getSkor()+
                "\n!!!!"+kazanan+" kazandı!!!!");
        
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıxBilg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıxBilg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıxBilg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıxBilg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıxBilg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
